



// Create new parents
POST {{$alpha_url_local}}/parent/create
Content-Type: {{$file_body_header}}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="username"

Souksavanh
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="example.jpg"
Content-Type: image/jpg

< ./assets/1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--



###

// update base on sending key
PUT {{$alpha_url_local}}/parent/update


###


DELETE {{$alpha_url_local}}/parent/delete/5f9c0cc92ecde731a886b812


###


GET {{$alpha_url_local}}/parent/list


###


GET {{$alpha_url_local}}/parent/list/5f9b886c43fa6e45c4337887